/*
RFC - 13
SECCION V -   Asignaciones e Incentivos (Pestaña subsidio por luto o sepelio)
QUITAR
Otorgar subsidio por gastos de sepelio
*/


-- SUBSIDIO POR FALLECIMIENTO
BEGIN TRY 
	DECLARE @V_MOTIVO_ACCION INT = 0
	SET @V_MOTIVO_ACCION = (SELECT MAX(ID_MOTIVO_ACCION) FROM  sistema.motivo_accion (NOLOCK))
	INSERT INTO sistema.motivo_accion
		(ID_ACCION, CODIGO_MOTIVO_ACCION, CODIGO_ORIGEN, DESCRIPCION_MOTIVO_ACCION, ES_VIGENTE, FECHA_INICIO_VIGENCIA, FECHA_CREACION, USUARIO_CREACION, ES_BORRADO)
	VALUES 
		(304, (@V_MOTIVO_ACCION + 1), 0, 'SUBSIDIO POR FALLECIMIENTO', 1, GETDATE(), GETDATE(), '42813053', 0)
	UPDATE sistema.motivo_accion SET ES_VIGENTE =0 WHERE ID_MOTIVO_ACCION IN (726)
	END TRY  
	BEGIN CATCH  
		SELECT         
			'Actualizar tabla transaccional.sancion_por_servidor_publico' AS OPERACION,
			ERROR_MESSAGE() AS MensajeError;  
END CATCH;  
GO


-- CREAR LA REGLA
DECLARE @CODIGO INT 
SELECT	@CODIGO = MAX(CODIGO_ENTIDAD_REGLA) + 1
	FROM	sistema.entidad_regla AS ER WITH (NOLOCK)
INSERT sistema.entidad_regla 
	(CODIGO_ENTIDAD_REGLA, ID_REGLA, ID_ENTIDAD, ID_REGISTRO_ENTIDAD, ES_VIGENTE, FECHA_CREACION, USUARIO_CREACION, ES_BORRADO, OBLIGATORIA)
VALUES
	(@CODIGO, 36, 23, 1898, 1, GETDATE(), '42813053', 0, 0)

-- QUITAR OTORGAR SUBSIDIO POR LUTO
update sistema.accion set ES_VIGENTE = 0 where ID_ACCION = 305


-- SUBSIDIO POR GASTOS DE SEPELIO O SERVICIO FUNERARIO COMPLETO
BEGIN TRY 
DECLARE @V_MOTIVO_ACCION INT = 0
SET @V_MOTIVO_ACCION = (SELECT MAX(ID_MOTIVO_ACCION) FROM  sistema.motivo_accion (NOLOCK))
	INSERT INTO sistema.motivo_accion
		(ID_ACCION, CODIGO_MOTIVO_ACCION, CODIGO_ORIGEN, DESCRIPCION_MOTIVO_ACCION, ES_VIGENTE, FECHA_INICIO_VIGENCIA, FECHA_CREACION, USUARIO_CREACION, ES_BORRADO)
	VALUES 
		(306, (@V_MOTIVO_ACCION + 1), 0, 'SUBSIDIO POR GASTOS DE SEPELIO O SERVICIO FUNERARIO COMPLETO', 1, GETDATE(), GETDATE(), '42813053', 0)
	-- QUITAR: OTORGAR SUBSIDIO POR LUTO Y GASTOS DE SEPELIO
	UPDATE sistema.motivo_accion SET ES_VIGENTE =0 WHERE ID_MOTIVO_ACCION IN (585)
END TRY  
BEGIN CATCH  
    SELECT         
		'Actualizar tabla transaccional.sancion_por_servidor_publico' AS OPERACION,
        ERROR_MESSAGE() AS MensajeError;  
END CATCH;  
GO	
	
-- Registro de regla
/*
- SUBSIDIO POR FALLECIMIENTO
- SUBSIDIO POR GASTOS DE SEPELIO O SERVICIO FUNERARIO COMPLETO
*/
DECLARE @ID_MOTIVO_ACCION INT = 1899
DECLARE @ID_COMPONENTE INT
DECLARE @ID_FORMULARIO INT
DECLARE @ID_COMPONENTE_FORMULARIO INT
DECLARE @ORDEN INT
DECLARE @ES_VISIBLE INT
DECLARE @ES_EDITABLE INT
DECLARE @ES_OBLIGATORIO INT
DECLARE @ES_VIGENTE INT
DECLARE @ES_BORRADO INT

DECLARE CURSOR_MOTIVO_ACCION_COMPONENTE_FORMULARIO CURSOR 
  LOCAL STATIC READ_ONLY FORWARD_ONLY
FOR 
SELECT 
	   ID_COMPONENTE,
	   ID_FORMULARIO, 
	   ID_COMPONENTE_FORMULARIO,
	   ORDEN, 
	   ES_VISIBLE,
	   ES_EDITABLE,
	   ES_OBLIGATORIO,
	   ES_VIGENTE,	   
	   ES_BORRADO
FROM sistema.motivo_accion_componente_formulario AS MC WITH (NOLOCK) WHERE	MC.ID_MOTIVO_ACCION IN (585) ORDER BY ORDEN ASC;  

OPEN CURSOR_MOTIVO_ACCION_COMPONENTE_FORMULARIO 
FETCH NEXT FROM CURSOR_MOTIVO_ACCION_COMPONENTE_FORMULARIO  INTO @ID_COMPONENTE, @ID_FORMULARIO, @ID_COMPONENTE_FORMULARIO, @ORDEN, @ES_VISIBLE, @ES_EDITABLE, @ES_OBLIGATORIO, @ES_VIGENTE, @ES_BORRADO
WHILE @@FETCH_STATUS = 0
BEGIN 
    --Do something with Id here
	PRINT @ID_MOTIVO_ACCION
	PRINT @ID_COMPONENTE
	PRINT @ID_FORMULARIO
	PRINT @ID_COMPONENTE_FORMULARIO
	PRINT @ORDEN
	PRINT @ES_VISIBLE
	PRINT @ES_EDITABLE
	PRINT @ES_OBLIGATORIO
	PRINT @ES_VIGENTE
	PRINT @ES_BORRADO

	INSERT INTO sistema.motivo_accion_componente_formulario 
		(ID_MOTIVO_ACCION, ID_COMPONENTE, ID_FORMULARIO, ID_COMPONENTE_FORMULARIO, ORDEN, ES_VISIBLE, ES_EDITABLE, ES_OBLIGATORIO, ES_VIGENTE, FECHA_CREA, USUARIO_CREA, ES_BORRADO)
	VALUES
		(@ID_MOTIVO_ACCION, @ID_COMPONENTE, @ID_FORMULARIO, @ID_COMPONENTE_FORMULARIO, @ORDEN, @ES_VISIBLE, @ES_EDITABLE, @ES_OBLIGATORIO, @ES_VIGENTE, GETDATE(), '42813053', @ES_BORRADO )

	FETCH NEXT FROM CURSOR_MOTIVO_ACCION_COMPONENTE_FORMULARIO INTO @ID_COMPONENTE, @ID_FORMULARIO, @ID_COMPONENTE_FORMULARIO, @ORDEN, @ES_VISIBLE, @ES_EDITABLE, @ES_OBLIGATORIO, @ES_VIGENTE, @ES_BORRADO
END
CLOSE CURSOR_MOTIVO_ACCION_COMPONENTE_FORMULARIO 
DEALLOCATE CURSOR_MOTIVO_ACCION_COMPONENTE_FORMULARIO 


--Regla de modificatoria 
/*
- SUBSIDIO POR FALLECIMIENTO
- SUBSIDIO POR GASTOS DE SEPELIO O SERVICIO FUNERARIO COMPLETO
*/
	
DECLARE @ID_ACCION_MODIFICATORIA INT
DECLARE @ID_MOTIVO_ACCION INT = 1899
DECLARE @ID_SITUACION_LABORAL INT
DECLARE @ES_VIGENTE INT
DECLARE @ES_BORRADO INT

DECLARE CURSOR_MODIFICATORIA_MOTIVO_ACCION CURSOR 
  LOCAL STATIC READ_ONLY FORWARD_ONLY
FOR 
SELECT 
	ID_ACCION_MODIFICATORIA,
	ID_SITUACION_LABORAL,
	ES_VIGENTE,
	ES_BORRADO
FROM parametrica.modificatoria_motivo_accion (NOLOCK) WHERE ID_MOTIVO_ACCION IN (585)  

OPEN CURSOR_MODIFICATORIA_MOTIVO_ACCION 
FETCH NEXT FROM CURSOR_MODIFICATORIA_MOTIVO_ACCION  INTO @ID_ACCION_MODIFICATORIA, @ID_SITUACION_LABORAL, @ES_VIGENTE, @ES_BORRADO
WHILE @@FETCH_STATUS = 0
BEGIN 
    --Do something with Id here
	PRINT @ID_ACCION_MODIFICATORIA
	PRINT @ID_MOTIVO_ACCION	
	PRINT @ID_SITUACION_LABORAL	
	PRINT @ES_VIGENTE
	PRINT @ES_BORRADO

	INSERT INTO parametrica.modificatoria_motivo_accion
		(ID_ACCION_MODIFICATORIA, ID_MOTIVO_ACCION, ID_SITUACION_LABORAL, ES_VIGENTE, FECHA_CREA, USUARIO_CREA, ES_BORRADO)
	VALUES 
		(@ID_ACCION_MODIFICATORIA, @ID_MOTIVO_ACCION, @ID_SITUACION_LABORAL, @ES_VIGENTE, GETDATE(), '42813053', @ES_BORRADO)

	FETCH NEXT FROM CURSOR_MODIFICATORIA_MOTIVO_ACCION INTO @ID_ACCION_MODIFICATORIA, @ID_SITUACION_LABORAL, @ES_VIGENTE, @ES_BORRADO
END
CLOSE CURSOR_MODIFICATORIA_MOTIVO_ACCION 
DEALLOCATE CURSOR_MODIFICATORIA_MOTIVO_ACCION 

/*
	REGISTRO DE CAMPO POR MOTIVO ACCION
*/
--ids motivo acccion anteriores
--585
--1899

DECLARE @ID_MOTIVO_ACCION INT = 1898
DECLARE @ID_CAMPO INT
DECLARE @ES_VIGENTE INT
DECLARE @ES_BORRADO INT

DECLARE CURSOR_CAMPO_MOTIVO_ACCION CURSOR 
  LOCAL STATIC READ_ONLY FORWARD_ONLY
FOR 
SELECT ID_CAMPO,
	   ES_VIGENTE,
       ES_BORRADO
FROM sistema.campo_motivo_accion (NOLOCK) WHERE ID_MOTIVO_ACCION = 726 AND ES_VIGENTE = 1

OPEN CURSOR_CAMPO_MOTIVO_ACCION 
FETCH NEXT FROM CURSOR_CAMPO_MOTIVO_ACCION  INTO @ID_CAMPO, @ES_VIGENTE, @ES_BORRADO
WHILE @@FETCH_STATUS = 0
BEGIN 
    --Do something with Id here
	PRINT @ID_CAMPO
	PRINT @ID_MOTIVO_ACCION	
	PRINT @ES_VIGENTE
	PRINT @ES_BORRADO

	INSERT INTO sistema.campo_motivo_accion
		(ID_CAMPO, ID_MOTIVO_ACCION, ES_VIGENTE, FECHA_CREACION, USUARIO_CREACION, ES_BORRADO)
	VALUES 
		(@ID_CAMPO, @ID_MOTIVO_ACCION, @ES_VIGENTE, GETDATE(), '42813053', @ES_BORRADO)

	FETCH NEXT FROM CURSOR_CAMPO_MOTIVO_ACCION INTO @ID_CAMPO, @ES_VIGENTE, @ES_BORRADO
END
CLOSE CURSOR_CAMPO_MOTIVO_ACCION 
DEALLOCATE CURSOR_CAMPO_MOTIVO_ACCION 