/*
RFC - 13
SECCION V -   Asignaciones e Incentivos (Pestaña subsidio por luto o sepelio)
QUITAR
Otorgar subsidio por gastos de sepelio
*/
UPDATE sistema.motivo_accion SET ES_VIGENTE =0 WHERE ID_MOTIVO_ACCION IN (726)

-- SUBSIDIO POR FALLECIMIENTO
DECLARE @V_MOTIVO_ACCION INT = 0
SET @V_MOTIVO_ACCION = (SELECT MAX(ID_MOTIVO_ACCION) FROM  sistema.motivo_accion (NOLOCK))
INSERT INTO sistema.motivo_accion
	(ID_ACCION, CODIGO_MOTIVO_ACCION, CODIGO_ORIGEN, DESCRIPCION_MOTIVO_ACCION, ES_VIGENTE, FECHA_INICIO_VIGENCIA, FECHA_CREACION, USUARIO_CREACION, ES_BORRADO)
VALUES 
	(304, (@V_MOTIVO_ACCION + 1), 0, 'SUBSIDIO POR FALLECIMIENTO', 1, GETDATE(), GETDATE(), '42813053', 0)

-- CREAR LA REGLA
DECLARE @CODIGO INT 
SELECT	@CODIGO = MAX(CODIGO_ENTIDAD_REGLA) + 1
	FROM	sistema.entidad_regla AS ER WITH (NOLOCK)
INSERT sistema.entidad_regla 
	(CODIGO_ENTIDAD_REGLA, ID_REGLA, ID_ENTIDAD, ID_REGISTRO_ENTIDAD, ES_VIGENTE, FECHA_CREACION, USUARIO_CREACION, ES_BORRADO, OBLIGATORIA)
VALUES
	(@CODIGO, 36, 23, 1898, 1, GETDATE(), '42813053', 0, 0)

-- QUITAR OTORGAR SUBSIDIO POR LUTO
update sistema.accion set ES_VIGENTE = 0 where ID_ACCION = 305

-- QUITAR: OTORGAR SUBSIDIO POR LUTO Y GASTOS DE SEPELIO
UPDATE sistema.motivo_accion SET ES_VIGENTE =0 WHERE ID_MOTIVO_ACCION IN (585)
-- SUBSIDIO POR GASTOS DE SEPELIO O SERVICIO FUNERARIO COMPLETO
DECLARE @V_MOTIVO_ACCION INT = 0
SET @V_MOTIVO_ACCION = (SELECT MAX(ID_MOTIVO_ACCION) FROM  sistema.motivo_accion (NOLOCK))
INSERT INTO sistema.motivo_accion
	(ID_ACCION, CODIGO_MOTIVO_ACCION, CODIGO_ORIGEN, DESCRIPCION_MOTIVO_ACCION, ES_VIGENTE, FECHA_INICIO_VIGENCIA, FECHA_CREACION, USUARIO_CREACION, ES_BORRADO)
VALUES 
	(306, (@V_MOTIVO_ACCION + 1), 0, 'SUBSIDIO POR GASTOS DE SEPELIO O SERVICIO FUNERARIO COMPLETO', 1, GETDATE(), GETDATE(), '42813053', 0)