IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE  TABLE_SCHEMA = 'transaccional' AND TABLE_NAME='accion_por_servidor_publico_datos_adicionales') 	    
BEGIN
	/****** Object:  Table [transaccional].[accion_por_servidor_publico_datos_adicionales]    Script Date: 11/05/2022 15:07:37 ******/
	SET ANSI_NULLS ON
	GO

	SET QUOTED_IDENTIFIER ON
	GO

	CREATE TABLE [transaccional].[accion_por_servidor_publico_datos_adicionales](
		[ID_ACCION_POR_SERVIDOR_PUBLICO_DATOS_ADICIONALES] [dbo].[identificador] IDENTITY(1,1) NOT NULL,
		[ID_ACCION_POR_SERVIDOR_PUBLICO] [int] NOT NULL,
		[SECCION] [dbo].[detalle500] NULL,
		[PESTANIA] [dbo].[detalle500] NULL,
		[FECHA_NOTIFICACION] [dbo].[fechausuario] NOT NULL,
		[FECHA_INICIO] [dbo].[fechausuario] NULL,
		[FECHA_FIN] [dbo].[fechausuario] NULL,
		[ANOTACIONES] [dbo].[detalle500] NULL,
		[ID_RESULTADO] [int] NULL,
		[DESCRIPCION_RESULTADO] [varchar](250) NULL,
		[ID_SEPARACION_PREVENTIVA] [int] NULL,
		[DESCRIPCION_SEPARACION_PREVENTIVA] [varchar](250) NULL,
		[FECHA_CREACION] [dbo].[fechausuario] NOT NULL,
		[USUARIO_CREACION] [dbo].[codigousuario] NOT NULL,
		[FECHA_MODIFICACION] [dbo].[fechausuario] NULL,
		[USUARIO_MODIFICACION] [dbo].[codigousuario] NULL,
		[ES_BORRADO] [dbo].[estado] NOT NULL,
	 CONSTRAINT [PK_ACCION_POR_SERVIDOR_PUBLICO_DATOS_ADICIONALES] PRIMARY KEY CLUSTERED 
	(
		[ID_ACCION_POR_SERVIDOR_PUBLICO_DATOS_ADICIONALES] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY],
	UNIQUE NONCLUSTERED 
	(
		[ID_ACCION_POR_SERVIDOR_PUBLICO] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]
	GO

END