-- REGISTRO DE NUEVO MOTIVO ACCION

INSERT INTO sistema.motivo_accion
	(ID_ACCION, CODIGO_MOTIVO_ACCION, CODIGO_ORIGEN, DESCRIPCION_MOTIVO_ACCION, ES_VIGENTE, FECHA_INICIO_VIGENCIA, FECHA_CREACION, USUARIO_CREACION, ES_BORRADO)
VALUES
	(43, @V_ID_MOTIVO_ACCION, @V_ID_MOTIVO_ACCION, 'LEY 27803 CESE COLECTIVO', 1, GETDATE(), GETDATE(), '42813053', 0)
	
--REGISTRO DE LOS MOTIVOS ACCION


DECLARE @ID_MOTIVO_ACCION INT = 1900
DECLARE @ID_COMPONENTE INT
DECLARE @ID_FORMULARIO INT
DECLARE @ID_COMPONENTE_FORMULARIO INT
DECLARE @ORDEN INT
DECLARE @ES_VISIBLE INT
DECLARE @ES_EDITABLE INT
DECLARE @ES_OBLIGATORIO INT
DECLARE @ES_VIGENTE INT
DECLARE @ES_BORRADO INT

DECLARE CURSOR_MOTIVO_ACCION_COMPONENTE_FORMULARIO CURSOR 
  LOCAL STATIC READ_ONLY FORWARD_ONLY
FOR 
SELECT 
	   ID_COMPONENTE,
	   ID_FORMULARIO, 
	   ID_COMPONENTE_FORMULARIO,
	   ORDEN, 
	   ES_VISIBLE,
	   ES_EDITABLE,
	   ES_OBLIGATORIO,
	   ES_VIGENTE,	   
	   ES_BORRADO
FROM sistema.motivo_accion_componente_formulario AS MC WITH (NOLOCK) WHERE	MC.ID_MOTIVO_ACCION IN (52, 1900) ORDER BY ORDEN ASC;  

OPEN CURSOR_MOTIVO_ACCION_COMPONENTE_FORMULARIO 
FETCH NEXT FROM CURSOR_MOTIVO_ACCION_COMPONENTE_FORMULARIO  INTO @ID_COMPONENTE, @ID_FORMULARIO, @ID_COMPONENTE_FORMULARIO, @ORDEN, @ES_VISIBLE, @ES_EDITABLE, @ES_OBLIGATORIO, @ES_VIGENTE, @ES_BORRADO
WHILE @@FETCH_STATUS = 0
BEGIN 
    --Do something with Id here
	PRINT @ID_MOTIVO_ACCION
	PRINT @ID_COMPONENTE
	PRINT @ID_FORMULARIO
	PRINT @ID_COMPONENTE_FORMULARIO
	PRINT @ORDEN
	PRINT @ES_VISIBLE
	PRINT @ES_EDITABLE
	PRINT @ES_OBLIGATORIO
	PRINT @ES_VIGENTE
	PRINT @ES_BORRADO

	INSERT INTO sistema.motivo_accion_componente_formulario 
		(ID_MOTIVO_ACCION, ID_COMPONENTE, ID_FORMULARIO, ID_COMPONENTE_FORMULARIO, ORDEN, ES_VISIBLE, ES_EDITABLE, ES_OBLIGATORIO, ES_VIGENTE, FECHA_CREA, USUARIO_CREA, ES_BORRADO)
	VALUES
		(@ID_MOTIVO_ACCION, @ID_COMPONENTE, @ID_FORMULARIO, @ID_COMPONENTE_FORMULARIO, @ORDEN, @ES_VISIBLE, @ES_EDITABLE, @ES_OBLIGATORIO, @ES_VIGENTE, GETDATE(), '42813053', @ES_BORRADO )

	FETCH NEXT FROM CURSOR_MOTIVO_ACCION_COMPONENTE_FORMULARIO INTO @ID_COMPONENTE, @ID_FORMULARIO, @ID_COMPONENTE_FORMULARIO, @ORDEN, @ES_VISIBLE, @ES_EDITABLE, @ES_OBLIGATORIO, @ES_VIGENTE, @ES_BORRADO
END
CLOSE CURSOR_MOTIVO_ACCION_COMPONENTE_FORMULARIO 
DEALLOCATE CURSOR_MOTIVO_ACCION_COMPONENTE_FORMULARIO 

-- REGISTRO DE LA REGLA

DECLARE @V_ID_ENTIDAD_REGLA INT
SELECT	@V_ID_ENTIDAD_REGLA = MAX(ID_ENTIDAD_REGLA)
FROM	sistema.entidad_regla AS ER WITH (NOLOCK)

SET @V_ID_ENTIDAD_REGLA = @V_ID_ENTIDAD_REGLA + 1
PRINT @V_ID_ENTIDAD_REGLA

INSERT INTO sistema.entidad_regla
	(CODIGO_ENTIDAD_REGLA, ID_REGLA, ID_ENTIDAD, ID_REGISTRO_ENTIDAD, ES_VIGENTE, FECHA_CREACION, USUARIO_CREACION, ES_BORRADO, OBLIGATORIA)
VALUES 
	(@V_ID_ENTIDAD_REGLA, 64, 23,1900, 1, GETDATE(), '42813053', 0,  0)


-- QUIAR EL PERMISO AL COMPONENTE DE CATEGORIA
SELECT * FROM sistema.motivo_accion_componente_formulario (NOLOCK) WHERE ID_MOTIVO_ACCION = 52
--UPDATE  sistema.motivo_accion_componente_formulario SET ES_BORRADO = 1 WHERE  ID_MOTIVO_ACCION_COMPONENTE_FORMULARIO = 2272

-- AGREGAR 	EL PERMISO PARA EL COMPONENTE DESARROLLADO POR ROBERT
--SELECT MAX(ID_MOTIVO_ACCION_COMPONENTE_FORMULARIO) FROM sistema.motivo_accion_componente_formulario  (NOLOCK) 11657

--INSERT INTO sistema.motivo_accion_componente_formulario 
--	(ID_MOTIVO_ACCION, ID_COMPONENTE_FORMULARIO, ORDEN, ES_VISIBLE, ES_EDITABLE, ES_OBLIGATORIO, ES_VIGENTE, FECHA_CREA, USUARIO_CREA, ES_BORRADO)
--VALUES
--	(52, 72, 9, 1,1,1,1, GETDATE(), '42813053', 0)